python .\run_model.py ^
--model-name NRMS-BERT ^
--reprocess-data ^
--regenerate-dataset ^
--max-dataset-size 10 ^
--epochs 5 ^
--learning-rate 1e-5 ^
--pretrained-model-name "distilbert-base-uncased" ^
--train-batch-size 16 ^
--eval-batch-size 32 ^
--num-heads 16 ^
--ckpt-dir "head-16" ^
--mode train